language: node_js
node_js:
  - "4.4"
  - "5.0"
  - "5.5"
  - "5.11"
  - "6.0"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true