language: node_js
node_js:
  - "4.8"
  - "5.12"
  - "6.11"
  - "7.10"
  - "8.1"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true
